# Многоязычные тексты для бота и веб-панели

BOT_TEXTS = {
    'ru': {
        'welcome': "Привет, {name}! 👋\n\nЯ бот для продажи VPN ключей. Выберите действие:",
        'buy_vpn': "💰 Купить VPN",
        'my_connections': "📊 Мои подключения", 
        'help': "ℹ️ Помощь",
        'admin_panel': "👑 Админ панель",
        'choose_tariff': "Выберите тариф:",
        'choose_payment': "Выберите способ оплаты:",
        'tariff_info': "Тариф: **{name}**\nЦена: **{price}₽**\nПериод: **{days} дней**\n\n",
        'yoomoney_pay': "💳 YooMoney",
        'stars_pay': "⭐ Telegram Stars",
        'back': "🔙 Назад",
        'payment_instructions': "Для оплаты перейдите по ссылке:\n{url}\n\nПосле оплаты нажмите кнопку проверки:",
        'check_payment': "✅ Проверить оплату",
        'payment_success': "✅ **Оплата подтверждена! VPN подключение активировано.**\n\n**Логин:** `{email}`\n**Тариф:** {tariff}\n**Действует до:** {expires}\n\nИнструкции по настройке будут отправлены в течение 5 минут.",
        'no_connections': "У вас нет активных подключений.",
        'user_connections': "**Ваши подключения:**\n\n",
        'connection_active': "✅ Активно",
        'connection_inactive': "❌ Неактивно",
        'valid_until': "Действует до: {date}",
        'help_text': "**ℹ️ Помощь**\n\n**Как купить VPN:**\n1. Нажмите '💰 Купить VPN'\n2. Выберите тариф\n3. Оплатите через YooMoney\n4. Нажмите 'Проверить оплату'\n\n**Проблемы с оплатой?**\nСвяжитесь с администратором: @admin\n\n**Техподдержка:**\nПо всем вопросам работы VPN обращайтесь к @support",
        'payment_not_found': "Оплата еще не поступила. Попробуйте позже.",
        'payment_error': "❌ Ошибка при создании платежа: {error}\n\nПопробуйте позже или свяжитесь с администратором.",
        'panel_error': "❌ Нет доступных панелей. Свяжитесь с администратором.",
        'activation_error': "❌ Ошибка при создании VPN подключения. Свяжитесь с администратором.",
        'language_changed': "🌐 Язык изменен на Русский",
        'change_language': "🌐 Сменить язык",
        'bot_description': "VPN бот для безопасного и быстрого доступа в интернет",
        'bot_instructions': "1. Нажмите /start для начала\n2. Выберите тариф\n3. Оплатите через YooMoney\n4. Получите VPN конфигурацию",
    },
    'en': {
        'welcome': "Hello, {name}! 👋\n\nI am a VPN key sales bot. Choose an action:",
        'buy_vpn': "💰 Buy VPN", 
        'my_connections': "📊 My Connections",
        'help': "ℹ️ Help",
        'admin_panel': "👑 Admin Panel",
        'choose_tariff': "Choose tariff:",
        'choose_payment': "Choose payment method:",
        'tariff_info': "Tariff: **{name}**\nPrice: **{price}₽**\nPeriod: **{days} days**\n\n",
        'yoomoney_pay': "💳 YooMoney",
        'stars_pay': "⭐ Telegram Stars", 
        'back': "🔙 Back",
        'payment_instructions': "For payment follow the link:\n{url}\n\nAfter payment click the check button:",
        'check_payment': "✅ Check Payment",
        'payment_success': "✅ **Payment confirmed! VPN connection activated.**\n\n**Login:** `{email}`\n**Tariff:** {tariff}\n**Valid until:** {expires}\n\nSetup instructions will be sent within 5 minutes.",
        'no_connections': "You have no active connections.",
        'user_connections': "**Your connections:**\n\n",
        'connection_active': "✅ Active",
        'connection_inactive': "❌ Inactive", 
        'valid_until': "Valid until: {date}",
        'help_text': "**ℹ️ Help**\n\n**How to buy VPN:**\n1. Click '💰 Buy VPN'\n2. Choose tariff\n3. Pay via YooMoney\n4. Click 'Check Payment'\n\n**Payment issues?**\nContact administrator: @admin\n\n**Support:**\nFor any VPN operation questions contact @support",
        'payment_not_found': "Payment not received yet. Try again later.",
        'payment_error': "❌ Payment creation error: {error}\n\nTry later or contact administrator.",
        'panel_error': "❌ No available panels. Contact administrator.",
        'activation_error': "❌ VPN connection creation error. Contact administrator.",
        'language_changed': "🌐 Language changed to English", 
        'change_language': "🌐 Change language",
        'bot_description': "VPN bot for secure and fast internet access",
        'bot_instructions': "1. Click /start to begin\n2. Choose your tariff\n3. Pay via YooMoney\n4. Get VPN configuration",
    }
}

WEB_TEXTS = {
    'ru': {
        'dashboard': 'Дашборд',
        'panels': 'Панели',
        'subscriptions': 'Подписки', 
        'users': 'Пользователи',
        'payments': 'Платежи',
        'alerts': 'Оповещения',
        'login': 'Вход',
        'login_title': 'VPN Admin Panel',
        'login_subtitle': 'Войдите в систему',
        'username': 'Имя пользователя',
        'password': 'Пароль',
        'sign_in': 'Войти',
        'get_access': 'Получите доступ у администратора бота',
        'total_users': 'Пользователи',
        'active_subs': 'Активные подписки',
        'active_panels': 'Активные панели',
        'total_revenue': 'Общий доход',
        'panel_status': 'Статус панелей',
        'recent_payments': 'Последние платежи',
        'active_alerts': 'Активные оповещения',
        'refresh': 'Обновить',
        'resolve': 'Решить',
        'no_alerts': 'Нет активных оповещений',
        'panel_management': 'Управление панелями',
        'add_panel': 'Добавить панель',
        'location': 'Локация',
        'url': 'URL',
        'clients': 'Клиенты',
        'last_check': 'Последняя проверка',
        'never': 'Никогда',
        'details': 'Детали',
        'enable': 'Включить',
        'disable': 'Выключить',
        'add_panel_modal': 'Добавить новую панель',
        'add_panel_instructions': 'Используйте команду в Telegram боте для добавления новых панелей:',
        'example': 'Пример',
        'system_management': 'Управление системой',
        'system_information': 'Информация о системе',
        'version_information': 'Информация о версии',
        'current_version': 'Текущая версия',
        'latest_version': 'Последняя версия',
        'update_available': 'Доступно обновление',
        'up_to_date': 'Актуальная версия',
        'update_system': 'Обновить систему',
        'update_information': 'Информация об обновлении',
        'bot_information': 'Информация о боте',
        'how_to_use': 'Как использовать',
        'features': 'Возможности',
        'secure_vpn_access': 'Безопасный VPN доступ',
        'fast_connection': 'Быстрое подключение',
        'easy_setup': 'Простая настройка',
        'support_24_7': 'Поддержка 24/7',
        'start_with_bot': 'Начать с бота Telegram',
        'invalid_credentials': 'Неверное имя пользователя или пароль',
    },
    'en': {
        'dashboard': 'Dashboard',
        'panels': 'Panels',
        'subscriptions': 'Subscriptions',
        'users': 'Users', 
        'payments': 'Payments',
        'alerts': 'Alerts',
        'login': 'Login',
        'login_title': 'VPN Admin Panel',
        'login_subtitle': 'Sign in',
        'username': 'Username',
        'password': 'Password',
        'sign_in': 'Sign In',
        'get_access': 'Get access from the bot administrator',
        'total_users': 'Users',
        'active_subs': 'Active Subscriptions',
        'active_panels': 'Active Panels', 
        'total_revenue': 'Total Revenue',
        'panel_status': 'Panel Status',
        'recent_payments': 'Recent Payments',
        'active_alerts': 'Active Alerts',
        'refresh': 'Refresh',
        'resolve': 'Resolve',
        'no_alerts': 'No active alerts',
        'panel_management': 'Panel Management',
        'add_panel': 'Add Panel',
        'location': 'Location',
        'url': 'URL',
        'clients': 'Clients',
        'last_check': 'Last Check',
        'never': 'Never',
        'details': 'Details',
        'enable': 'Enable',
        'disable': 'Disable',
        'add_panel_modal': 'Add New Panel',
        'add_panel_instructions': 'Use the command in the Telegram bot to add new panels:',
        'example': 'Example',
        'system_management': 'System Management',
        'system_information': 'System Information', 
        'version_information': 'Version Information',
        'current_version': 'Current Version',
        'latest_version': 'Latest Version',
        'update_available': 'Update Available',
        'up_to_date': 'Up to Date',
        'update_system': 'Update System',
        'update_information': 'Update Information',
        'bot_information': 'Bot Information',
        'how_to_use': 'How to Use',
        'features': 'Features',
        'secure_vpn_access': 'Secure VPN Access',
        'fast_connection': 'Fast Connection',
        'easy_setup': 'Easy Setup',
        'support_24_7': '24/7 Support',
        'start_with_bot': 'Start with Telegram Bot',
        'invalid_credentials': 'Invalid username or password',
    }
}

def get_bot_text(language, key, **kwargs):
    """Получить текст для бота на указанном языке"""
    text = BOT_TEXTS.get(language, BOT_TEXTS['en']).get(key, key)
    return text.format(**kwargs) if kwargs else text

def get_web_text(language, key, **kwargs):
    """Получить текст для веб-панели на указанном языке"""
    text = WEB_TEXTS.get(language, WEB_TEXTS['en']).get(key, key)
    return text.format(**kwargs) if kwargs else text
